/// lib/firebase_options.dart
/// ==========================
/// Firebase project configuration — generated by FlutterFire CLI.
///
/// HOW TO GENERATE THIS FILE:
///   1. Install FlutterFire CLI:
///        dart pub global activate flutterfire_cli
///
///   2. In the flutter_app directory, run:
///        flutterfire configure
///
///   3. Select your Firebase project from the list
///
///   4. The CLI overwrites this file with your real project credentials
///
/// ⚠️  NEVER commit real API keys to git.
///     Add firebase_options.dart to .gitignore
///     OR use environment-based config for production.
///
/// NOTE:
/// Android values below are set from `android/app/google-services.json`.
/// iOS/web/macos values are still placeholders until those platform apps are
/// configured in Firebase console.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS:     return ios;
      case TargetPlatform.macOS:   return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for ${defaultTargetPlatform.name}',
        );
    }
  }

  // ── Run `flutterfire configure` to fill these in ──────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:            'YOUR-WEB-API-KEY',
    authDomain:        'YOUR-PROJECT.firebaseapp.com',
    projectId:         'YOUR-PROJECT-ID',
    storageBucket:     'YOUR-PROJECT.appspot.com',
    messagingSenderId: 'YOUR-SENDER-ID',
    appId:             'YOUR-WEB-APP-ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:            'AIzaSyDXnlEOZMFpIoJAjTSjRUEyjIfp31gCV7c',
    appId:             '1:292484877265:android:8c4dc7afb7a9e05acceef0',
    messagingSenderId: '292484877265',
    projectId:         'trading-app-4ab30',
    storageBucket:     'trading-app-4ab30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:            'YOUR-IOS-API-KEY',
    appId:             'YOUR-IOS-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId:         'YOUR-PROJECT-ID',
    storageBucket:     'YOUR-PROJECT.appspot.com',
    iosBundleId:       'com.yourname.aiTrader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey:            'YOUR-MACOS-API-KEY',
    appId:             'YOUR-MACOS-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId:         'YOUR-PROJECT-ID',
    storageBucket:     'YOUR-PROJECT.appspot.com',
    iosBundleId:       'com.yourname.aiTrader',
  );
}
